#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Sat May 11 23:04:18 2024
#

import wx

# begin wxGlade: dependencies
import wx.grid
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((900, 600))
        self.SetTitle("Organizador de materias - BlahCorp")

        self.panel_1 = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel_1.SetMinSize((300, 500))
        self.panel_1.SetScrollRate(10, 10)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.grilla_estudiantes = wx.grid.Grid(self.panel_1, wx.ID_ANY, size=(1, 1))
        self.grilla_estudiantes.CreateGrid(30, 18)
        self.grilla_estudiantes.SetSelectionMode(wx.grid.Grid.SelectColumns)
        self.grilla_estudiantes.SetColLabelValue(0, "Estudiantes")
        self.grilla_estudiantes.SetColSize(0, 10)
        self.grilla_estudiantes.SetColLabelValue(1, "Algebra")
        self.grilla_estudiantes.SetColSize(1, 1)
        self.grilla_estudiantes.SetColLabelValue(2, "Arts")
        self.grilla_estudiantes.SetColSize(2, 1)
        self.grilla_estudiantes.SetColLabelValue(3, "Biology")
        self.grilla_estudiantes.SetColSize(3, 1)
        self.grilla_estudiantes.SetColLabelValue(4, "Citizenship")
        self.grilla_estudiantes.SetColSize(4, 1)
        self.grilla_estudiantes.SetColLabelValue(5, "Computer\nScience")
        self.grilla_estudiantes.SetColSize(5, 1)
        self.grilla_estudiantes.SetColLabelValue(6, "Desarrollo\nHumano")
        self.grilla_estudiantes.SetColSize(6, 1)
        self.grilla_estudiantes.SetColLabelValue(7, "English")
        self.grilla_estudiantes.SetColSize(7, 1)
        self.grilla_estudiantes.SetColLabelValue(8, u"Estadística")
        self.grilla_estudiantes.SetColSize(8, 1)
        self.grilla_estudiantes.SetColLabelValue(9, u"Filosofía")
        self.grilla_estudiantes.SetColSize(9, 1)
        self.grilla_estudiantes.SetColLabelValue(10, u"Física")
        self.grilla_estudiantes.SetColSize(10, 1)
        self.grilla_estudiantes.SetColLabelValue(11, "Geography")
        self.grilla_estudiantes.SetColSize(11, 1)
        self.grilla_estudiantes.SetColLabelValue(12, u"Geometría")
        self.grilla_estudiantes.SetColSize(12, 1)
        self.grilla_estudiantes.SetColLabelValue(13, "Historia")
        self.grilla_estudiantes.SetColSize(13, 1)
        self.grilla_estudiantes.SetColLabelValue(14, "Lenguaje")
        self.grilla_estudiantes.SetColSize(14, 1)
        self.grilla_estudiantes.SetColLabelValue(15, u"Ortografía")
        self.grilla_estudiantes.SetColSize(15, 1)
        self.grilla_estudiantes.SetColLabelValue(16, "Physical\nEducation")
        self.grilla_estudiantes.SetColSize(16, 1)
        self.grilla_estudiantes.SetColLabelValue(17, u"Química")
        self.grilla_estudiantes.SetColSize(17, 1)
        self.grilla_estudiantes.SetMinSize((350, 450))
        sizer_1.Add(self.grilla_estudiantes, 1, wx.EXPAND, 0)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_2.Add((50, 50), 0, 0, 0)

        self.boton_aceptar = wx.Button(self.panel_1, wx.ID_ANY, "Aceptar")
        sizer_2.Add(self.boton_aceptar, 0, 0, 0)

        sizer_2.Add((100, 50), 0, 0, 0)

        self.boton_borrar = wx.Button(self.panel_1, wx.ID_ANY, "Borrar")
        sizer_2.Add(self.boton_borrar, 0, 0, 0)

        sizer_2.Add((50, 50), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.panel_organizador = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.panel_organizador)
        self.panel_organizador.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
